# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffd8dd27e4fd6eadab99f785b8330cc0256439192ed4951aac40188489ba5b4106aca0bbe374514421f91c70f6e2d88706b2f5c0656432dfb8ddf0409d0f6108

test:
  secret_key_base: c2d7055d3f0cf9bf4d86863b4e7511dbfc6e942e0abcb794ccdb5f56f4a518c6aeec3fca30cc00056654a77a51c4289547121dca8a85096c04d723c75db49282

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
